name: Deploy to Netlify

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Deploy to Netlify
        uses: netlify/actions/cli@v2
        with:
          publish-dir: ./public
          production-deploy: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }} # Set this secret in your GitHub repo
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }} # Set this secret in your GitHub repo
